data:
  base_path: 'data/'
  task_path: 'en-10k/'
  task_id: 1
  PAD_ID: 0

model:
  use_pretrained: true
  embed_dim: 50
  encoder_type: UNI
  cell_type: GRU
  num_layers: 1
  num_units: 64
  memory_hob: 3
  dropout: 0.0
  reg_scale: 0.001

train:
  batch_size: 64
  learning_rate: 0.0003
  train_steps: 100000
  model_dir: 'logs/bAbi_task1'
  save_checkpoints_steps: 1000
  check_hook_n_iter: 1000
  min_eval_frequency: 1000
  optimizer: 'Adam'

eval:
  batch_size: -1
