data:
  base_path: 'data/'
  task_id: 1
  PAD_ID: 0

model:
  use_pretrained: false
  embed_dim: 8
  encoder_type: UNI
  cell_type: GRU
  num_layers: 1
  num_units: 4
  memory_hob: 1
  dropout: 0.5

train:
  batch_size: 1
  learning_rate: 0.001
  train_steps: 10000
  model_dir: 'logs/check_tiny'
  save_checkpoints_steps: 1000
  check_hook_n_iter: 10
  min_eval_frequency: 10
