data:
  base_path: 'data/'
  task_path: 'en/'
  task_id: 1
  PAD_ID: 0

model:
  batch_size: 2
  use_pretrained: false
  embed_dim: 8
  encoder_type: UNI
  cell_type: GRU
  num_layers: 2
  num_units: 16
  memory_hob: 2
  dropout: 0.5
  reg_scale: 0.001

train:
  learning_rate: 0.001
  optimizer: 'Adam'

  train_steps: 10000
  model_dir: 'logs/check_tiny'

  save_checkpoints_steps: 1000
  check_hook_n_iter: 100
  min_eval_frequency: 100

  print_verbose: False
  debug: False
